#
# ~/.bash_profile
#

if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi

# added by Anaconda3 5.1.0 installer
#export PATH="/anaconda3/bin:$PATH"

# Added by Krypton
export GPG_TTY=$(tty)

# added by Anaconda3 5.2.0 installer
# export PATH="/Users/brandonrandle/anaconda3/bin:$PATH"
