#
# ~/.bashrc
#

# source git-completion script for git autocomplete
source ~/.env/git-completion.bash

# PLATFORM DETERMINATION
PLATFORM='unknown'
UNAMESTR=`uname`
if [[ "$UNAMESTR" == 'Linux' ]]; then
    PLATFORM='linux'
elif [[ "$UNAMESTR" == 'Darwin' ]]; then
    PLATFORM='mac'
fi

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# PROMPT
force_color_prompt=yes
PS1='\[\e[32m\]\$: \[\e[37m\]'

# SET DEFAULT EDITOR
export VISUAL=vim
export EDITOR="$VISUAL"

# SET PATH
export PATH=${PATH}:${HOME}/bin

# ALIASES
if [[ $PLATFORM == 'linux' ]]; then
    alias ls='ls --color=auto -x'
elif [[ $PLATFORM == 'mac' ]]; then
    alias ls='ls -G -x'
fi

# pyenv initialization settings
# export WORKON_HOME=~/.ve
# export PROJECT_HOME=~/workspace
# eval "$(pyenv init -)"
# pyenv virtualenvwrapper_lazy
