" MY SETUP
" Brandon Randle
" github.com/brandonrandle/.env

" Clear compatibility settings
set nocompatible
set noshowmode

" ########## PATHOGEN ##########
execute pathogen#infect()
filetype plugin indent on

" GRUVBOX
set t_Co=256
colorscheme gruvbox
set background=dark

" VIM-AIRLINE
set laststatus=2

" ########## BASIC SETTINGS ##########

" ENCODING
set encoding=utf-8

" KEY MAPPINGS
inoremap jk <ESC>

" SYNTAX HIGHLIGHTING
syntax enable
autocmd! bufreadpost *.md set syntax=off
let python_hightlight_all = 1

" TABS TO SPACES
set ts=4
set expandtab

" LINE NUMBERS
set number
set numberwidth=4
set relativenumber

" MATCHING PAREN/BRACES/BRACKETS
set showmatch

" VISUAL LINE FOR CURSOR
set cursorline

" Set column limit to 80
set colorcolumn=80

" ########## LEARN VIMSCRIPT THE HARD WAY EXERCISES ##########
" Maps - to delete a line and paste it below the current line
map - ddp
