" MY SETUP
" Brandon Randle
" github.com/brandonrandle/.env

" COMPATIBILITY SETTINGS
set nocompatible
set noshowmode

" ################################ PLUGINS ################################

call plug#begin('~/.vim/plugged')
Plug 'morhetz/gruvbox'
Plug 'tmhedberg/SimpylFold'
Plug 'leafgarland/typescript-vim'
Plug 'vim-airline/vim-airline'
Plug 'nathangrigg/vim-beancount'
Plug 'airblade/vim-gitgutter'
Plug 'farmergreg/vim-lastplace'
Plug 'mhinz/vim-startify'
call plug#end()

" GRUVBOX
set t_Co=256
colorscheme gruvbox
set background=dark

" VIM-AIRLINE
set laststatus=2

" SIMPYLFOLD
" Remap space to toggle folds
nnoremap <space> za
" Set folds to be open by default
set foldlevel=99

" VIM-LASTPLACE
" No settings needed.

" VIM-GUTTER
" Adjusts updatetime to allow diff markers to appear quickly.
set updatetime=100

" ############################# BASIC SETTINGS #############################

" ENCODING
set encoding=utf-8

" KEY MAPPINGS
" Makes escaping from modes easier.
inoremap jk <ESC>

" GIVE BACKSPACE SOME POWER
set backspace=indent,eol,start

" SYNTAX HIGHLIGHTING
syntax enable

" DEFAULT WHITESPACE MANAGEMENT
set tabstop=4
set shiftwidth=4
set expandtab

" LINE NUMBERS
set number
set numberwidth=4
set relativenumber

" MATCHING PAREN/BRACES/BRACKETS
set showmatch

" VISUAL LINE FOR CURSOR
set cursorline

" SET WINDOW LIMIT
set colorcolumn=79
set textwidth=79

" REMOVE ALL TRAILING WHITESPACE WITH F5
nnoremap <F5> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar>:w<Bar><CR>


" ######################### FILE SPECIFIC SETTINGS #########################

" PYTHON Settings
au BufNewFile,BufRead *.py
    \set tabstop=4
    \set softtabstop=4
    \set shiftwidth=4
    \set autoindent
    \set fileformat=unix
    \let python_hightlight_all = 1

" MARKDOWN Settings
au BufNewFile,BufFilePre,BufRead *.md set filetype=markdown
au Filetype markdown setlocal ts=2 sw=2

" HTML Settings
"autocmd BufNewFile,BufFilePre,BufRead *.html
au Filetype html
    \set tabstop=2
    \set softtabstop=2
    \set shiftwidth=2
    \set autoindent
    \set expandtab
" autocmd Filetype html setlocal ts=2 sw=2

" TWIG Settings
" .twig files use html syntax
au BufNewFile,BufRead *.twig setlocal filetype=html

" YAML Settings
au BufNewFile,BufRead *.yml setlocal filetype=yaml
au Filetype yaml setlocal ts=2 expandtab sw=2 softtabstop=2
