" MY SETUP
" Brandon Randle
" github.com/brandonrandle/.env

" COMPATIBILITY SETTINGS
set nocompatible
set noshowmode


" ################################ PATHOGEN ################################
execute pathogen#infect()
filetype plugin indent on

" GRUVBOX
set t_Co=256
colorscheme gruvbox
set background=dark

" VIM-AIRLINE
set laststatus=2

" SIMPYLFOLD
" Remap space to toggle folds
nnoremap <space> za
" Set folds to be open by default
set foldlevel=99

" VIM-LASTPLACE

" VIM-GUTTER
" Adjusts updatetime to allow diff markers to appear quickly.
set updatetime=100

" ############################# BASIC SETTINGS #############################

" ENCODING
set encoding=utf-8

" KEY MAPPINGS
inoremap jk <ESC>

" GIVE BACKSPACE SOME POWER
set backspace=indent,eol,start

" SYNTAX HIGHLIGHTING
syntax enable

" DEFAULT WHITESPACE MANAGEMENT
set tabstop=4
set shiftwidth=4
set expandtab

" LINE NUMBERS
set number
set numberwidth=4
set relativenumber

" MATCHING PAREN/BRACES/BRACKETS
set showmatch

" VISUAL LINE FOR CURSOR
set cursorline

" SET WINDOW LIMIT
set colorcolumn=79
set textwidth=79

" REMOVE ALL TRAILING WHITESPACE WITH F5
nnoremap <F5> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar>:w<Bar><CR>

" SET NETRW DEFAULTS
 let g:netrw_banner = 0
" let g:netrw_liststyle = 3
" let g:netrw_browse_split = 4
" let g:netrw_altv = 1
" let g:netrw_winsize = 25
" augroup ProjectDrawer
"  autocmd!
"   autocmd VimEnter * :Vexplore
" augroup END


" ######################### FILE SPECIFIC SETTINGS #########################

" PYTHON Settings
au BufNewFile,BufRead *.py
    \set tabstop=4
    \set softtabstop=4
    \set shiftwidth=4
    \set autoindent
    \set fileformat=unix
    \let python_hightlight_all = 1

" MARKDOWN Settings
au BufNewFile,BufFilePre,BufRead *.md set filetype=markdown
au Filetype markdown setlocal ts=2 sw=2

" HTML Settings
"autocmd BufNewFile,BufFilePre,BufRead *.html
au Filetype html
    \set tabstop=2
    \set softtabstop=2
    \set shiftwidth=2
    \set autoindent
    \set expandtab
" autocmd Filetype html setlocal ts=2 sw=2

" TWIG Settings
" .twig files use html syntax
au BufNewFile,BufRead *.twig setlocal filetype=html

" YAML Settings
au BufNewFile,BufRead *.yml setlocal filetype=yaml
au Filetype yaml setlocal ts=2 expandtab sw=2 softtabstop=2


" ################# LEARN VIMSCRIPT THE HARD WAY EXERCISES #################


" ################### TEMP SETTINGS FOR EXPERIMENTATION ####################
